parameters:
    nelmio_security.nonce_generator.number_of_bytes: 16

services:
    nelmio_security.csp_listener:
        class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        tags:
            - { name: kernel.event_subscriber }
        factory_class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        factory_method: fromConfig

    nelmio_security.csp_reporter_controller:
        class: Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController
        arguments: ['@logger']

    nelmio_security.nonce_generator:
        class: Nelmio\SecurityBundle\ContentSecurityPolicy\NonceGenerator
        arguments: ["@security.secure_random", "%nelmio_security.nonce_generator.number_of_bytes%"]

    nelmio_security.sha_computer:
        class: Nelmio\SecurityBundle\ContentSecurityPolicy\ShaComputer
        arguments: ["%nelmio_security.csp.hash_algorith%"]
