services:
    nelmio_security.csp_listener:
        class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        tags:
            - { name: kernel.event_subscriber }
        factory_class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        factory_method: fromConfig

    nelmio_security.csp_reporter_controller:
        class: Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController
        arguments: ['@logger']
