parameters:
    nelmio_security.nonce_generator.number_of_bytes: 16
    nelmio_security.ua_parser.service: nelmio_security.ua_parser.ua_php

services:
    nelmio_security.ua_parser.ua_php:
        class: Nelmio\SecurityBundle\UserAgent\UAParserUserAgentParser
        public: false
        arguments: ['@nelmio_security.ua_parser.ua_php.provider']

    nelmio_security.ua_parser.ua_php.provider:
        class: UAParser\Parser
        public: false
        factory_class: UAParser\Parser
        factory_method: create

    nelmio_security.policy_manager:
        public: false
        class: Nelmio\SecurityBundle\ContentSecurityPolicy\PolicyManager

    nelmio_security.csp_listener:
        class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        tags:
            - { name: kernel.event_subscriber }
        factory_class: Nelmio\SecurityBundle\EventListener\ContentSecurityPolicyListener
        factory_method: fromConfig

    nelmio_security.csp_reporter_controller:
        class: Nelmio\SecurityBundle\Controller\ContentSecurityPolicyController
        arguments: ['@logger']

    nelmio_security.nonce_generator:
        class: Nelmio\SecurityBundle\ContentSecurityPolicy\NonceGenerator
        arguments: ["%nelmio_security.nonce_generator.number_of_bytes%"]

    nelmio_security.sha_computer:
        class: Nelmio\SecurityBundle\ContentSecurityPolicy\ShaComputer
        arguments: ["%nelmio_security.csp.hash_algorithm%"]
