services:
    nelmio_security.session.handler:
        class: Nelmio\SecurityBundle\Session\CookieSessionHandler
        arguments:
            - '%nelmio_security.cookie_session.name%'
            - '%nelmio_security.cookie_session.lifetime%'
            - '%nelmio_security.cookie_session.path%'
            - '%nelmio_security.cookie_session.domain%'
            - '%nelmio_security.cookie_session.secure%'
            - '%nelmio_security.cookie_session.httponly%'
            - '@logger'

        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 9998 }
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -9998 }
