services:
    nelmio_security.referrer_policy_listener:
        class: Nelmio\SecurityBundle\EventListener\ReferrerPolicyListener
        arguments:
            - '%nelmio_security.referrer_policy.policies%'

        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
