name: Continuous Integration

on: [push, pull_request]

jobs:
  tests:
    name: PHP ${{ matrix.php-version }} + Symfony ${{ matrix.symfony-version }} + ${{ matrix.dependencies }}

    runs-on: ubuntu-latest

    env:
      SYMFONY_DEPRECATIONS_HELPER: max[self]=99999
      SYMFONY_REQUIRE: ${{ matrix.symfony-version }}

    strategy:
      matrix:
        php-version:
          - 7.0
          - 7.1
          - 7.2
          - 7.3
          - 7.4
          - 8.0
          - 8.1
        symfony-version:
          - 3.4
          - 4.4.x
          - 5.4.x
        dependencies:
          - highest
        include:
          - php-version: 5.5
            dependencies: lowest
            symfony-version: 2.8
          - php-version: 5.6
            dependencies: highest
            symfony-version: 2.8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          ini-values: memory_limit=-1, date.timezone=Europe/Paris, session.gc_probability=0
          php-version: ${{ matrix.php-version }}
          tools: composer:v2,flex

      - name: Install Composer dependencies (${{ matrix.dependencies }})
        uses: ramsey/composer-install@v1
        with:
            dependency-versions: ${{ matrix.dependencies }}

      - name: Run tests
        run: vendor/bin/simple-phpunit
